---
- name: Example Playbook with Conditionals
  hosts: all
  gather_facts: yes

  tasks:
    - name: Check OS and perform tasks accordingly
      debug:
        msg: "Performing RedHat-specific task"
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Another task for Debian-based systems
      debug:
        msg: "Performing Debian-specific task"
      when: ansible_facts['os_family'] == 'Debian'

